fn main() {
  if std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() == "espidf" {
    embuild::espidf::sysenv::output();
  }

  let out_dir = std::env::var("OUT_DIR").unwrap();
  let out_path = std::path::PathBuf::from(&out_dir);
  // OUT_DIR is target/<triple>/<profile>/build/<crate-hash>/out
  // We go up 3 levels to reach target/<triple>/<profile>/
  let bin_dir = out_path.ancestors().nth(3).unwrap();

  println!(
    "cargo:rustc-link-arg=-Wl,-Map={}/linker.map",
    bin_dir.display()
  );

  if let Err(e) = generate_img_data("./img", "./src/img") {
    panic!("Failed to generate image data: {e}");
  }

  if let Err(e) = generate_buttplug_data("./src/buttplug/data") {
    panic!("Failed to generate Buttplug data: {e}");
  }
}

fn generate_img_data(img_dir: &str, out_dir: &str) -> anyhow::Result<()> {
  let on = image::Rgb([255, 255, 255]);

  std::fs::create_dir_all(&out_dir)?;
  let img_dir = std::path::Path::new(img_dir).canonicalize()?;
  let out_dir = std::path::Path::new(out_dir).canonicalize()?;

  let mut images = Vec::<(String, u32)>::new();

  for entry in std::fs::read_dir(img_dir)? {
    let entry = entry?;
    let path = entry.path();
    if path.is_file() {
      let out_path = out_dir
        .join(path.file_name().unwrap())
        .with_extension("bin");
      let img = image::open(&path)?.to_rgb8();
      let row_width_bytes = (img.width() as usize + 7) / 8;
      let mut out = vec![0; img.height() as usize * row_width_bytes];

      // Turn into 1bpp data, row by row
      // Each row needs to be padded to a byte boundary
      for y in 0..img.height() {
        for x in 0..img.width() {
          let pixel = img.get_pixel(x, y);
          let bit = if *pixel == on { 1 } else { 0 };
          let byte_index = (y as usize * row_width_bytes) + (x as usize / 8);
          out[byte_index] |= bit << (7 - (x % 8));
        }
      }
      images.push((
        out_path.file_name().unwrap().to_string_lossy().to_string(),
        img.width(),
      ));
      write_if_different(out_path, &out)?;
    }
  }
  let code = images
      .iter()
      .map(|(name, width)| format!("#[rustfmt::skip]\npub const {}: ::embedded_graphics::image::ImageRaw<embedded_graphics::pixelcolor::BinaryColor> = ::embedded_graphics::image::ImageRaw::new(include_bytes!(\"./{}\"), {});", name.trim_end_matches(".bin").to_uppercase(), name, width))
      .collect::<Vec<_>>()
      .join("\n");

  write_if_different(
    out_dir.join("mod.rs"),
    format!(
      "// This file is generated by build.rs. Do not edit manually.\n\n{}",
      code
    ),
  )?;

  Ok(())
}

mod buttplug_data {
  use std::{collections::HashMap, ops::Deref, sync::Arc};

  use buttplug_server_device_config::{
    BaseDeviceIdentifier,
    ProtocolCommunicationSpecifier,
    ServerDeviceDefinition,
    load_protocol_configs,
  };
  use compact_str::CompactString;
  use rustc_hash::FxBuildHasher;
  use serde::Serialize;
  use serde_describe::SelfDescribed;

  #[derive(Debug, Serialize)]
  pub struct ButtplugData {
    // Use FxHashMap to keep consistent ordering of keys across builds, which helps with reproducible builds
    // It will still deserialize into a regular HashMap, so this is just for serialization stability
    base_communication_specifiers:
      HashMap<CompactString, Vec<ProtocolCommunicationSpecifier>, FxBuildHasher>,
    base_device_definitions: Vec<(ServerDeviceDefinition, Vec<BaseDeviceIdentifier>)>,
    base_device_definitions_count: usize,
  }

  impl ButtplugData {
    pub fn build() -> anyhow::Result<Vec<u8>> {
      let dcm = load_protocol_configs(&None, &None, false)?.finish()?;

      let data = Self {
        base_communication_specifiers: dcm
          .base_communication_specifiers()
          .iter()
          .map(|(k, v)| (k.clone(), v.clone()))
          .collect(),
        base_device_definitions: {
          let mut base_device_definitions_groups: HashMap<
            *const ServerDeviceDefinition,
            (ServerDeviceDefinition, Vec<BaseDeviceIdentifier>),
          > = HashMap::new();

          // Collect into FxHashMap first to ensure stable ordering of keys across builds, which helps with reproducible builds
          let base_device_definitions = dcm
            .base_device_definitions()
            .iter()
            .map(|(i, d)| (i.clone(), d))
            .collect::<HashMap<_, _, FxBuildHasher>>();

          for (identifier, definition) in base_device_definitions {
            base_device_definitions_groups
              .entry(Arc::as_ptr(definition))
              .or_insert_with(|| (definition.deref().clone(), Vec::new()))
              .1
              .push(identifier);
          }

          // Serialize as Vec<(ServerDeviceDefinition, Vec<BaseDeviceIdentifier>)>
          base_device_definitions_groups
            .into_values()
            .map(|(def, ids)| (def, ids))
            .collect()
        },
        base_device_definitions_count: dcm.base_device_definitions().len(),
      };

      Ok(postcard::to_allocvec(&SelfDescribed(&data))?)
    }
  }
}

fn generate_buttplug_data(out_dir: &str) -> anyhow::Result<()> {
  std::fs::create_dir_all(&out_dir)?;
  let out_dir = std::path::Path::new(out_dir).canonicalize()?;

  let data = buttplug_data::ButtplugData::build()?;
  write_if_different(out_dir.join("data.bin"), &data)?;
  write_if_different(out_dir.join("data.bin.gz"), miniz_oxide::deflate::compress_to_vec(&data, 6))?;

  Ok(())
}

fn write_if_different<P, C>(path: P, data: C) -> std::io::Result<()>
where
  P: AsRef<std::path::Path>,
  C: AsRef<[u8]>,
{
  if path.as_ref().exists() {
    let existing_data = std::fs::read(path.as_ref())?;
    if existing_data == data.as_ref() {
      return Ok(());
    }
  }
  std::fs::write(path, data)
}
