// Central registry of model asset URLs.
// All files are imported via Vite so they get content-hashed filenames in the
// build output and missing files produce build errors.
//
// Source files live in docs/models/ and are generated by docs_build.py.

// ── GLB files (3D viewer) ──────────────────────────────────────────────────

export { default as assemblyGlb } from "~/models/assembly.glb";
export { default as pcbGlb } from "~/models/pcb.glb";
export { default as caseGlb } from "~/models/case.glb";
export { default as encoderKnobGlb } from "~/models/encoder_knob.glb";
export { default as sliderKnobGlb } from "~/models/slider_knob.glb";
export { default as powerSwitchCapGlb } from "~/models/power_switch_cap.glb";

// ── STEP files (downloads) ─────────────────────────────────────────────────

export { default as caseTopStepUrl } from "~/models/case_top.step?url";
export { default as caseBottomStepUrl } from "~/models/case_bottom.step?url";
export { default as encoderKnobStepUrl } from "~/models/encoder_knob.step?url";
export { default as sliderKnobStepUrl } from "~/models/slider_knob.step?url";
export { default as powerSwitchCapStepUrl } from "~/models/power_switch_cap.step?url";
