fn main() {
  if std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default() == "espidf" {
    embuild::espidf::sysenv::output();
  }

  let out_dir = std::env::var("OUT_DIR").unwrap();
  let out_path = std::path::PathBuf::from(&out_dir);
  // OUT_DIR is target/<triple>/<profile>/build/<crate-hash>/out
  // We go up 3 levels to reach target/<triple>/<profile>/
  let bin_dir = out_path.ancestors().nth(3).unwrap();

  println!(
    "cargo:rustc-link-arg=-Wl,-Map={}/linker.map",
    bin_dir.display()
  );

  if let Err(e) = generate_img_data("./img", "./src/img") {
    panic!("Failed to generate image data: {e}");
  }

  if let Err(e) = generate_buttplug_data("./src/buttplug/data") {
    panic!("Failed to generate Buttplug data: {e}");
  }
}

fn generate_img_data(img_dir: &str, out_dir: &str) -> anyhow::Result<()> {
  let on = image::Rgb([255, 255, 255]);

  std::fs::create_dir_all(&out_dir)?;

  let img_dir = std::path::Path::new(img_dir).canonicalize()?;
  let out_dir = std::path::Path::new(out_dir).canonicalize()?;

  let mut images = Vec::<(String, u32)>::new();

  for entry in std::fs::read_dir(img_dir)? {
    let entry = entry?;
    let path = entry.path();
    if path.is_file() {
      let out_path = out_dir
        .join(path.file_name().unwrap())
        .with_extension("bin");
      let img = image::open(&path)?.to_rgb8();
      let row_width_bytes = (img.width() as usize + 7) / 8;
      let mut out = vec![0; img.height() as usize * row_width_bytes];

      // Turn into 1bpp data, row by row
      // Each row needs to be padded to a byte boundary
      for y in 0..img.height() {
        for x in 0..img.width() {
          let pixel = img.get_pixel(x, y);
          let bit = if *pixel == on { 1 } else { 0 };
          let byte_index = (y as usize * row_width_bytes) + (x as usize / 8);
          out[byte_index] |= bit << (7 - (x % 8));
        }
      }
      images.push((
        out_path.file_name().unwrap().to_string_lossy().to_string(),
        img.width(),
      ));
      std::fs::write(out_path, &out)?;
    }
  }
  let code = images
      .iter()
      .map(|(name, width)| format!("#[rustfmt::skip]\npub const {}: ::embedded_graphics::image::ImageRaw<embedded_graphics::pixelcolor::BinaryColor> = ::embedded_graphics::image::ImageRaw::new(include_bytes!(\"./{}\"), {});", name.trim_end_matches(".bin").to_uppercase(), name, width))
      .collect::<Vec<_>>()
      .join("\n");

  std::fs::write(
    out_dir.join("mod.rs"),
    format!(
      "// This file is generated by build.rs. Do not edit manually.\n\n{}",
      code
    ),
  )?;

  Ok(())
}

fn generate_buttplug_data(out_dir: &str) -> anyhow::Result<()> {
  use std::collections::HashMap;

  use buttplug_server_device_config::{ProtocolCommunicationSpecifier, load_protocol_configs};
  use miniz_oxide::deflate::compress_to_vec;
  use rustc_hash::FxBuildHasher;

  std::fs::create_dir_all(&out_dir)?;

  let dcm = load_protocol_configs(&None, &None, false)?.finish()?;

  let base_communication_specifiers: Vec<_> = dcm
    .base_communication_specifiers()
    .iter()
    .filter_map(|(protocol_name, specs)| {
      let specs: Vec<_> = specs
        .iter()
        .cloned()
        .filter(|spec| match spec {
          ProtocolCommunicationSpecifier::BluetoothLE(_) => true,
          _ => false,
        })
        .collect();
      if specs.is_empty() {
        None
      } else {
        Some((protocol_name.clone(), specs))
      }
    })
    .collect();

  let base_communication_specifiers_postcard = postcard::to_stdvec(&base_communication_specifiers)?;

  std::fs::write(
    [&out_dir, "base_communication_specifiers.postcard.bin"]
      .iter()
      .collect::<std::path::PathBuf>(),
    &base_communication_specifiers_postcard,
  )?;

  std::fs::write(
    [&out_dir, "base_communication_specifiers.postcard.bin.gz"]
      .iter()
      .collect::<std::path::PathBuf>(),
    compress_to_vec(&base_communication_specifiers_postcard, 6),
  )?;

  let base_device_definitions: HashMap<_, _, FxBuildHasher> = dcm
    .base_device_definitions()
    .iter()
    .filter_map(|(identifier, definition)| Some((identifier.clone(), definition.clone())))
    .collect();

  let base_device_definitions_postcard = postcard::to_stdvec(&base_device_definitions)?;

  std::fs::write(
    [&out_dir, "base_device_definitions.postcard.bin"]
      .iter()
      .collect::<std::path::PathBuf>(),
    &base_device_definitions_postcard,
  )?;

  std::fs::write(
    [&out_dir, "base_device_definitions.postcard.bin.gz"]
      .iter()
      .collect::<std::path::PathBuf>(),
    compress_to_vec(&base_device_definitions_postcard, 6),
  )?;

  Ok(())
}
