// This file is generated by build.rs. Do not edit manually.

#[rustfmt::skip]
pub const LOGO: ::embedded_graphics::image::ImageRaw<embedded_graphics::pixelcolor::BinaryColor> = ::embedded_graphics::image::ImageRaw::new(include_bytes!("./logo.bin"), 64);